account_id = "574fdb1eae7e80782a805c4b92f6b626"
compatibility_date = "2022-05-14"
name = "remix-cloudflare-worker-template"

main = "entry.worker.ts"

workers_dev = true

[build]
command = "npm run build"

[site]
bucket = "public"

[env.dev]
SESSION_SECRET = "this-should-be-secure-in-production"

[durable_objects]
bindings = [
  {name = "CHAT_ROOM", class_name = "ChatRoomDurableObject"},
  {name = "COUNTER", class_name = "CounterDurableObject"},
  {name = "RATE_LIMITER", class_name = "RateLimiterDurableObject"},
]

[[migrations]]
new_classes = ["CounterDurableObject"]
tag = "v1"

[[migrations]]
new_classes = ["ChatRoomDurableObject", "RateLimiterDurableObject"]
tag = "v2"
